name: Specs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: crystal tool format --check
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
